const SEV_RANK = { critical: 0, high: 1, moderate: 2, low: 3, unknown: 4 };

export function parseSeverityThreshold(value = 'critical') {
  const normalized = String(value || 'critical').toLowerCase();
  return Object.hasOwn(SEV_RANK, normalized) ? normalized : 'critical';
}

export function isAtOrAboveSeverity(severity, threshold = 'critical') {
  const sev = SEV_RANK[severity] ?? SEV_RANK.unknown;
  const limit = SEV_RANK[parseSeverityThreshold(threshold)];
  return sev <= limit;
}

export function getVulnKey(service, vuln) {
  return [
    service.name,
    vuln.packageName,
    vuln.packageVersion,
    vuln.id,
    vuln.cveId || '',
    vuln.ghsaId || '',
  ].join('|');
}

export function flattenVulns(payload) {
  const rows = [];
  for (const service of payload.services || []) {
    for (const vuln of service.vulns || []) {
      rows.push({ service, vuln, key: getVulnKey(service, vuln) });
    }
  }
  return rows;
}

export function buildDiffReport(currentPayload, baselinePayload = { services: [] }) {
  const current = flattenVulns(currentPayload);
  const baseline = flattenVulns(baselinePayload);
  const currentMap = new Map(current.map(row => [row.key, row]));
  const baselineMap = new Map(baseline.map(row => [row.key, row]));

  const added = current.filter(row => !baselineMap.has(row.key));
  const resolved = baseline.filter(row => !currentMap.has(row.key));
  const unchanged = current.filter(row => baselineMap.has(row.key));

  return {
    added,
    resolved,
    unchanged,
    summary: {
      added: added.length,
      resolved: resolved.length,
      unchanged: unchanged.length,
      current: current.length,
      baseline: baseline.length,
      addedBySeverity: countBySeverity(added),
      currentBySeverity: countBySeverity(current),
    },
  };
}

export function shouldFailForSeverity(payloadOrDiff, threshold) {
  const rows = Array.isArray(payloadOrDiff?.added)
    ? payloadOrDiff.added
    : flattenVulns(payloadOrDiff);
  return rows.some(({ vuln }) => isAtOrAboveSeverity(vuln.severity, threshold));
}

export function buildMarkdownReport(currentPayload, diffReport = null) {
  const totalServices = currentPayload.services?.length || 0;
  const totalPackages = (currentPayload.services || []).reduce((sum, svc) => sum + (svc.totalPackages || 0), 0);
  const totalVulns = flattenVulns(currentPayload).length;
  const severity = aggregateSeverity(currentPayload);
  const lines = [
    '## osv-ui CVE report',
    '',
    `Scanned ${totalServices} service(s), ${totalPackages} package(s), ${totalVulns} vulnerability finding(s).`,
    '',
    '| Severity | Count |',
    '|---|---:|',
    `| Critical | ${severity.critical} |`,
    `| High | ${severity.high} |`,
    `| Moderate | ${severity.moderate} |`,
    `| Low | ${severity.low} |`,
    `| Unknown | ${severity.unknown} |`,
  ];

  if (diffReport) {
    lines.push(
      '',
      '### PR diff',
      '',
      '| Status | Count |',
      '|---|---:|',
      `| New | ${diffReport.summary.added} |`,
      `| Resolved | ${diffReport.summary.resolved} |`,
      `| Unchanged | ${diffReport.summary.unchanged} |`,
    );
    appendFindingList(lines, 'New findings', diffReport.added);
    appendFindingList(lines, 'Resolved findings', diffReport.resolved);
  } else {
    appendFindingList(lines, 'Top findings', flattenVulns(currentPayload).slice(0, 20));
  }

  lines.push('', '_Generated by osv-ui._');
  return lines.join('\n');
}

export function buildCycloneDxSbom(payload) {
  const components = [];
  const seen = new Set();
  for (const service of payload.services || []) {
    for (const pkg of service.packages || []) {
      const key = `${pkg.ecosystem}:${pkg.name}@${pkg.version}`;
      if (seen.has(key)) continue;
      seen.add(key);
      components.push({
        type: 'library',
        name: pkg.name,
        version: pkg.version,
        purl: buildPurl(pkg),
        scope: pkg.dev ? 'optional' : 'required',
        properties: [
          { name: 'osv-ui:ecosystem', value: pkg.ecosystem || '' },
          { name: 'osv-ui:direct', value: String(!!pkg.isDirect) },
        ],
      });
    }
  }

  const vulnerabilities = flattenVulns(payload).map(({ service, vuln }) => ({
    id: vuln.cveId || vuln.id,
    source: { name: 'OSV', url: vuln.osvUrl },
    ratings: [{
      severity: vuln.severity === 'moderate' ? 'medium' : vuln.severity,
      score: vuln.cvssScore || undefined,
      method: vuln.cvssScore ? 'CVSSv3' : undefined,
    }],
    description: vuln.title,
    affects: [{
      ref: buildPurl({
        ecosystem: vuln.ecosystem,
        name: vuln.packageName,
        version: vuln.packageVersion,
      }),
    }],
    advisories: (vuln.references || []).map(url => ({ url })),
    properties: [
      { name: 'osv-ui:service', value: service.name },
      { name: 'osv-ui:fixedIn', value: vuln.fixedIn || '' },
    ],
  }));

  return {
    bomFormat: 'CycloneDX',
    specVersion: '1.5',
    version: 1,
    metadata: {
      timestamp: payload.scannedAt || new Date().toISOString(),
      tools: [{ vendor: 'osv-ui', name: 'osv-ui' }],
    },
    components,
    vulnerabilities,
  };
}

export function buildSpdxSbom(payload) {
  const now = payload.scannedAt || new Date().toISOString();
  const packages = [];
  const seen = new Set();
  for (const service of payload.services || []) {
    for (const pkg of service.packages || []) {
      const key = `${pkg.ecosystem}:${pkg.name}@${pkg.version}`;
      if (seen.has(key)) continue;
      seen.add(key);
      packages.push({
        name: pkg.name,
        SPDXID: spdxId(pkg),
        versionInfo: pkg.version,
        downloadLocation: pkg.registry || 'NOASSERTION',
        filesAnalyzed: false,
        externalRefs: [{
          referenceCategory: 'PACKAGE-MANAGER',
          referenceType: 'purl',
          referenceLocator: buildPurl(pkg),
        }],
      });
    }
  }

  return {
    spdxVersion: 'SPDX-2.3',
    dataLicense: 'CC0-1.0',
    SPDXID: 'SPDXRef-DOCUMENT',
    name: 'osv-ui-sbom',
    documentNamespace: `https://osv-ui.local/sbom/${Date.now()}`,
    creationInfo: {
      created: now,
      creators: ['Tool: osv-ui'],
    },
    packages,
  };
}

export async function sendWebhook(url, payload, { threshold = 'critical', diffReport = null } = {}) {
  if (!url) return null;
  const rows = diffReport ? diffReport.added : flattenVulns(payload);
  const findings = rows.filter(({ vuln }) => isAtOrAboveSeverity(vuln.severity, threshold));
  if (findings.length === 0) {
    return { sent: false, reason: 'no findings matched threshold' };
  }

  const body = {
    tool: 'osv-ui',
    scannedAt: payload.scannedAt,
    threshold: parseSeverityThreshold(threshold),
    totalFindings: flattenVulns(payload).length,
    matchedFindings: findings.length,
    findings: findings.slice(0, 20).map(({ service, vuln }) => ({
      service: service.name,
      package: vuln.packageName,
      version: vuln.packageVersion,
      severity: vuln.severity,
      id: vuln.cveId || vuln.id,
      title: vuln.title,
      fixedIn: vuln.fixedIn || null,
      url: vuln.osvUrl,
    })),
  };

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(10000),
  });
  if (!res.ok) throw new Error(`Webhook returned ${res.status}`);
  return { sent: true, status: res.status, findings: findings.length };
}

function aggregateSeverity(payload) {
  const counts = { critical: 0, high: 0, moderate: 0, low: 0, unknown: 0 };
  for (const service of payload.services || []) {
    for (const [severity, count] of Object.entries(service.severity || {})) {
      counts[severity] = (counts[severity] || 0) + count;
    }
  }
  return counts;
}

function countBySeverity(rows) {
  const counts = { critical: 0, high: 0, moderate: 0, low: 0, unknown: 0 };
  for (const { vuln } of rows) {
    counts[vuln.severity] = (counts[vuln.severity] || 0) + 1;
  }
  return counts;
}

function appendFindingList(lines, title, rows) {
  lines.push('', `### ${title}`);
  if (!rows.length) {
    lines.push('', 'None.');
    return;
  }
  lines.push('', '| Severity | Service | Package | Advisory | Fix |', '|---|---|---|---|---|');
  for (const { service, vuln } of rows.slice(0, 20)) {
    lines.push(`| ${vuln.severity} | ${service.name} | ${vuln.packageName}@${vuln.packageVersion} | ${vuln.cveId || vuln.id} | ${vuln.fixedIn || '-'} |`);
  }
  if (rows.length > 20) lines.push(`| ... | ... | ... | ${rows.length - 20} more | ... |`);
}

function buildPurl(pkg) {
  const name = encodeURIComponent(pkg.name || '').replace(/%2F/g, '/');
  const version = pkg.version ? `@${encodeURIComponent(pkg.version)}` : '';
  const type = purlType(pkg.ecosystem);
  return `pkg:${type}/${name}${version}`;
}

function purlType(ecosystem) {
  if (ecosystem === 'npm') return 'npm';
  if (ecosystem === 'PyPI') return 'pypi';
  if (ecosystem === 'Go') return 'golang';
  if (ecosystem === 'crates.io') return 'cargo';
  if (ecosystem === 'Maven') return 'maven';
  if (ecosystem === 'Packagist') return 'composer';
  if (ecosystem === 'RubyGems') return 'gem';
  return String(ecosystem || 'generic').toLowerCase();
}

function spdxId(pkg) {
  return `SPDXRef-Package-${String(pkg.ecosystem || 'pkg')}-${String(pkg.name || 'unknown')}-${String(pkg.version || 'unknown')}`
    .replace(/[^A-Za-z0-9.-]/g, '-');
}
